language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - cmake -DGMOCK_ROOT=/usr/src/gmock ..

script:
  - cmake --build .
  - "cd alterate-math/test && ctest -V && cd -"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
      - libboost-all-dev

notifications:
  email:
    - vyacheslav.mayorov@gmail.com
