language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install libgtest-dev
  - pushd
  - cd /usr/src/gtest
  - sudo cmake -DCMAKE_BUILD_TYPE=DEBUG .
  - sudo cmake --build .
  - sudo mv libgtest.a /usr/local/lib/libgtestd.a
  - sudo mv libgtest_main.a /usr/local/lib/libgtest_maind.a
  - sudo cmake -DCMAKE_BUILD_TYPE=RELEASE .
  - sudo cmake --build .
  - sudo mv libgtest.a /usr/local/lib/libgtest.a
  - sudo mv libgtest_main.a /usr/local/lib/libgtest_main.a
  - popd

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: cmake --build build
