language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
  - cd /usr/src/gtest
  - sudo cmake -DCMAKE_BUILD_TYPE=DEBUG .
  - sudo cmake --build .
  - sudo mv libgtest.a /usr/local/lib/libgtestd.a
  - sudo mv libgtest_main.a /usr/local/lib/libgtest_maind.a
  - sudo cmake -DCMAKE_BUILD_TYPE=RELEASE .
  - sudo cmake --build .
  - sudo mv libgtest.a /usr/local/lib/libgtest.a
  - sudo mv libgtest_main.a /usr/local/lib/libgtest_main.a
  - cd -

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
  - "cd alterate-math/test && ctest -V && cd -"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
      - libgtest-dev
      - libboost-all-dev

notifications:
  email:
    - vyacheslav.mayorov@gmail.com
